export const PUT_COMPANY_DATA_SUCCESS = 'PUT_COMPANY_DATA_SUCCESS';
export const POST_COMPANY_DATA_SUCCESS = 'POST_COMPANY_DATA_SUCCESS';
export const POST_COMPANY_DATA_FAIL = 'POST_COMPANY_DATA_FAIL';


export const POST_COMPANY_LOGO_SUCCESS = 'POST_COMPANY_LOGO_SUCCESS';

export const ARCHIVE_COMPANY_SUCCESS = 'ARCHIVE_COMPANY_SUCCESS';
export const UNARCHIVE_COMPANY_SUCCESS = 'UNARCHIVE_COMPANY_SUCCESS';


export const SET_COMPANY = 'SET_COMPANY';
